### ISSUE TITLE
Midi file don't play to end

### ISSUE THREAD

**Issue by No-User** [SammyIAm/Moppy2#22]
Value on end timer does not mach the end time ot the midi file.
And midi file don't play to it's end.

**Comment by Lothean** [comment]
Hello!
Could you please attach your MIDI so I can take a look ?

**Comment by No-User** [comment]
[Despacito.zip](https://github.com/SammyIAm/Moppy2/files/2280864/Despacito.zip)
Here it is

**Comment by No-User** [comment]
Lol,yes sorry for trouble.
