### ISSUE TITLE
MoppyControlGui wont open in Lubuntu

### ISSUE THREAD

**Issue by Machinegamer101** [SammyIAm/Moppy2#25]
i have a laptop that i been using for using moppy, the thing is that the gui is not opening anymore
the gui is the java one

**Comment by SammyIAm** [comment]
If you attempt to launch the GUI from the command line, do you get any
output?

Also, there should be log files in the Moppy GUI directory (or near by).
If you can share any of that Information it may be helpful.

**Comment by Machinegamer101** [comment]
the log files were empty, but i fixed it already! i needed to modify a file in the java folder (/etc/java-8-openjdk) called "accessibility.properties" that included the assistive technologies as org.GNOME.Accesibility.AtkWrapper thanks for try to help me!
