### ISSUE TITLE
Hard Disk as kick instrument?

### ISSUE THREAD

**Issue by DrW0if** [SammyIAm/Moppy2#30]
Is it possible to use Hard disks with Moppy? I've already used moppy with floppy drives and on youtube I've seen also hdds and printers, but on this repository there's nothing for HDDs. Thanks a lot for your work!

**Comment by DJthefirst** [comment]
I’ve had Success soldering two bread board wires directly to the hdd motor putting one to ground and one to the pwm pin of the default floppiedrive settups  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DrW0if** [comment]
I'll try, thanks a lot!

**Comment by jaidenortiz7** [comment]
> I’ve had Success soldering two bread board wires directly to the hdd motor putting one to ground and one to the pwm pin of the default floppiedrive settups
> 
> Sent with [GitHawk](http://githawk.com)

I know this is kind of an old thread but how should I wire the cables to the HDD from the Arduino?

**Comment by SammyIAm** [comment]
Closing in favor of Issue #44
