### ISSUE TITLE
Problem with >11 floppies + Question

### ISSUE THREAD

**Issue by THLCX** [SammyIAm/Moppy2#43]
Hello

There is a problem with the file FloppyDrives.cpp :  
Only 11 floppies are supported, 16 are not because of implementation holes.

I fixed everything :  
[ThomasCyrix.com/files/FloppyDrives.cpp](url)

Also, I can't find a way to simply select or unselected which channel will be active when playing the music.
It was a good feature in the 1st version of Moppy, is an update to add some easy and fast interface about this planned ?

Thanks for your work

**Comment by C288** [comment]
I have an arduino mega 2560. I have 16 drives connected but can't get all of them to work. How would I do this?

**Comment by SammyIAm** [comment]
Closing due to lack of response, feel free to reopen if you've still got questions.
